apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uvhfmkv29-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uvhfmkv29-nodejs 
  name: uvhfmkv29-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: uvhfmkv29-nodejs 
